version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_ROOT_PASSWORD: app
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'

#  mysql:
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_DATABASE: app
#      MYSQL_USER: app
#      MYSQL_PASSWORD: app
#      MYSQL_ROOT_PASSWORD: app
#    ports:
#      - "127.0.0.1:3306:3306"


  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stomp listeners [{61613, [{default_user, <<\"guest\">>}, {default_pass, <<\"guest\">>}]}]"
    ports:
        - "15672:15672"
        - "5672:5672"
        - "61613:61613"
    command: [
        "bash", "-c",
        "chmod 400 /var/lib/rabbitmq/.erlang.cookie; 
            rabbitmq-plugins enable rabbitmq_management;
            rabbitmq-plugins enable rabbitmq_stomp;
            rabbitmq-server" ]
#    && rabbitmq_management
#    networks:
#      - rabbitmq_go_net


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    ports:
      - "8081:8081"
    environment:
#      - SPRING_PROFILES_ACTIVE= docker-compose
       SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/app'
       SPRING_DATASOURCE_USERNAME: app
       SPRING_DATASOURCE_PASSWORD: app
       SPRING_RABBITMQ_HOST: rabbitmq
       SPRING_RABBITMQ_PORT: 5672
       SPRING_RABBITMQ_USERNAME: guest
       SPRING_RABBITMQ_PASSWORD: guest
       SPRING_RABBITMQ_STOMP_RELAY_HOST: rabbitmq
       SPRING_RABBITMQ_STOMP_RELAY_PORT: 61613
       SPRING_RABBITMQ_STOMP_RELAY_LOGIN: guest
       SPRING_RABBITMQ_STOMP_RELAY_PASSCODE: guest

#networks:
#  rabbitmq_go_net:
#    driver: bridge